#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and:
#   "bad luck from China" in the fourth line
#   "bad luck from Japan" in the nineth line
#   "bad luck from Italy" in the seventeenth line

count=1

while [ $count -le 20 ]
do
  echo "$count"
  case $count in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( count++ ))
done
